package entite;
// Generated 2018-09-28 16:50:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Docteur generated by hbm2java
 */
public class Docteur  implements java.io.Serializable {


     private String matricule;
     private Specialite specialite;
     private String nomm;
     private String ville;
     private String adresse;
     private Byte niveau;
     private Integer nbrpatients;
     private Set consultations = new HashSet(0);
     private Set dossierpatients = new HashSet(0);

    public Docteur() {
    }

	
    public Docteur(String matricule, Specialite specialite, String nomm) {
        this.matricule = matricule;
        this.specialite = specialite;
        this.nomm = nomm;
    }
    public Docteur(String matricule, Specialite specialite, String nomm, String ville, String adresse, Byte niveau, Integer nbrpatients, Set consultations, Set dossierpatients) {
       this.matricule = matricule;
       this.specialite = specialite;
       this.nomm = nomm;
       this.ville = ville;
       this.adresse = adresse;
       this.niveau = niveau;
       this.nbrpatients = nbrpatients;
       this.consultations = consultations;
       this.dossierpatients = dossierpatients;
    }
   
    public String getMatricule() {
        return this.matricule;
    }
    
    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }
    public Specialite getSpecialite() {
        return this.specialite;
    }
    
    public void setSpecialite(Specialite specialite) {
        this.specialite = specialite;
    }
    public String getNomm() {
        return this.nomm;
    }
    
    public void setNomm(String nomm) {
        this.nomm = nomm;
    }
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public Byte getNiveau() {
        return this.niveau;
    }
    
    public void setNiveau(Byte niveau) {
        this.niveau = niveau;
    }
    public Integer getNbrpatients() {
        return this.nbrpatients;
    }
    
    public void setNbrpatients(Integer nbrpatients) {
        this.nbrpatients = nbrpatients;
    }
    public Set getConsultations() {
        return this.consultations;
    }
    
    public void setConsultations(Set consultations) {
        this.consultations = consultations;
    }
    public Set getDossierpatients() {
        return this.dossierpatients;
    }
    
    public void setDossierpatients(Set dossierpatients) {
        this.dossierpatients = dossierpatients;
    }




}


