package entite;
// Generated 2018-09-28 16:50:26 by Hibernate Tools 4.3.1



/**
 * OrdonnancemedicamentsId generated by hbm2java
 */
public class OrdonnancemedicamentsId  implements java.io.Serializable {


     private String numord;
     private String idmed;

    public OrdonnancemedicamentsId() {
    }

    public OrdonnancemedicamentsId(String numord, String idmed) {
       this.numord = numord;
       this.idmed = idmed;
    }
   
    public String getNumord() {
        return this.numord;
    }
    
    public void setNumord(String numord) {
        this.numord = numord;
    }
    public String getIdmed() {
        return this.idmed;
    }
    
    public void setIdmed(String idmed) {
        this.idmed = idmed;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrdonnancemedicamentsId) ) return false;
		 OrdonnancemedicamentsId castOther = ( OrdonnancemedicamentsId ) other; 
         
		 return ( (this.getNumord()==castOther.getNumord()) || ( this.getNumord()!=null && castOther.getNumord()!=null && this.getNumord().equals(castOther.getNumord()) ) )
 && ( (this.getIdmed()==castOther.getIdmed()) || ( this.getIdmed()!=null && castOther.getIdmed()!=null && this.getIdmed().equals(castOther.getIdmed()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNumord() == null ? 0 : this.getNumord().hashCode() );
         result = 37 * result + ( getIdmed() == null ? 0 : this.getIdmed().hashCode() );
         return result;
   }   


}


